name: Docker Build && Push Image

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2
    - name: Env
      run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort 
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        driver: docker-container
        driver-opts: image=moby/buildkit:master
        buildkitd-flags: --debug
        config: .github/buildkitd.toml
        install: true
    #- name: Docker meta
    #  id: meta
    #  uses: docker/metadata-action@v4
    #  with:
    #    flavor: |
    #      latest=true
    #    tags: |
    #      type=schedule,enable=true,priority=1000
    - name: Inspect builder
      run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        target: openjij-builder
        cache-from: type=gha
        cache-to: type=gha,mode=max
   
